package:
    name: mznb
    version: "1.0"

source:
    path: ../src

build:
    noarch: python
    number: 1
    string: snapshot
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

about:
    home: http://github.com/pdenno/mznb/
    license: Mozilla Public License 2.0 (MPL 2.0)
    
